apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-config
  namespace: default
data:
  REDIS_CONNECTION: "redis-service.default.svc.cluster.local:6379"
  LOG_LEVEL: "Information"
  WORKER_POLL_DELAY_MS: "500"
  WORKER_PROCESS_DELAY_MS: "2000"
  TCP_PORT: "9000"
  UDP_PORT: "9001"
  RABBITMQ_HOST: "rabbitmq-service"
  OUTBOX_POLL_DELAY_MS: "1000"
  OUTBOX_DB_PATH: "outbox.db"